### ISSUE TITLE
请教Localcache的问题

### ISSUE THREAD

**Issue by junp** [QzoneTouch/commonWidget#3]
看到Localcache更新缓存，是通过get方法获取，
READMD里提到 **Compatible with both ios(5,6,7) and android(2.3~4.2)** ，
在 http://caniuse.com/#feat=xhr2 上看到，有部分浏览器版本对xhr2的支持不是很好，这个存在跨域问题吗？

**Comment by QzoneTouch** [comment]
这个需要储存js文件的服务器在下发文件时带上cross-origin的头，允许访问的域获取文件。

``` javascript
Access-Control-Allow-Origin:http://domain.com
```
